# FROM tensorflow/tensorflow:devel-gpu
FROM tensorflow/tensorflow:latest     

RUN pip install --upgrade pip && pip install \
    pillow \
    paho-mqtt \
    pydantic \
    PyYAML
    #tensorflow

WORKDIR /app

CMD ["sleep", "infinity"]