# FROM tensorflow/tensorflow:devel-gpu
FROM tensorflow/tensorflow:latest     

# cv2 dependencies
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install --upgrade pip && pip install \
    pillow \
    paho-mqtt \
    pydantic \
    PyYAML \
    matplotlib \
    opencv-python

WORKDIR /app

CMD ["sleep", "infinity"]
# CMD ["python", "server/server_object_detection.py"]