FROM armindocachada/tensorflow2-opencv4-raspberrypi4:2.2_4.5.0

RUN pip install --upgrade pip && pip install \
    paho-mqtt \
    pydantic \
    PyYAML \
    matplotlib \
    keras 

WORKDIR /app/server


# CMD ["sleep", "infinity"]
CMD ["python3", "server_object_detection.py"]