FROM armindocachada/tensorflow2-opencv4-raspberrypi4:2.2_4.5.0

RUN pip install --upgrade pip && pip install \
    paho-mqtt \
    pydantic \
    PyYAML \
    matplotlib 

WORKDIR /app


# CMD ["sleep", "infinity"]
CMD ["python3", "server/server_object_detection.py"]