FROM python:3.8-bullseye

# # cv2 dependencies
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y
RUN apt-get install python3-pip -y

RUN apt-get update && apt-get install libxcb-xinerama0

RUN pip install --upgrade pip && pip install \
    paho-mqtt \
    pydantic \
    PyYAML \
    PyQt5 \
    opencv-python-headless

WORKDIR /app

ENV QT_GRAPHICSSYSTEM="native"
ENV DISPLAY $DISPLAY

CMD ["sleep", "infinity"]