services:
  ai_server:
    image: tensorflow/tensorflow:devel-gpu

    container_name: ai_server

    build:
      context: .
      dockerfile: dockerfile_server

    volumes:
      - .:/app

    ports:
      - 1881:1883


  ai_client:
    image: python:3.8-bullseye

    container_name: ai_client

    build:
      context: .
      dockerfile: dockerfile_client

    volumes:
      - .:/app

    ports:
      - 1882:1883


  mqtt_broker:
    image: eclipse-mosquitto:2.0.15

    container_name: mqtt_broker

    build:
      context: .
      dockerfile: dockerfile_broker

    volumes:
      - .:/app

    ports:
      - 1883:1883