version: '3'
services:
  ai_server:
    image: armindocachada/tensorflow2-opencv4-raspberrypi4:2.2_4.5.0

    container_name: ai_server_pi

    build:
      context: .
      dockerfile: dockerfile_server_pi

    volumes:
      - .:/app

    ports:
      - 1881:1881

    networks:
      mqtt:
        ipv4_address: 172.20.0.3

    # networks:
    #   - default_net


  # ai_server:
  #   image: tensorflow/tensorflow:latest

  #   container_name: ai_server

  #   build:
  #     context: .
  #     dockerfile: dockerfile_server

  #   volumes:
  #     - .:/app

  #   ports:
  #     - 1881:1881

  #   networks:
  #     - default_net


  flask_server:
    image: python:3.8-bullseye

    container_name: flask_server

    build:
      context: .
      dockerfile: dockerfile_flask

    volumes:
      - .:/app

    ports:
      - 5000:5000

    networks:
        mqtt:
          ipv4_address: 172.20.0.4
    # networks:
    #   - default_net

  mqtt_broker:
    image: eclipse-mosquitto:2.0.15

    container_name: mqtt_broker

    build:
      context: .
      dockerfile: dockerfile_broker

    restart: always

    volumes:
      - .:/app
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    ports:
      - 1883:1883
      - 9001:9001

    networks:
      mqtt:
        ipv4_address: 172.20.0.5

# networks:
#   default_net:
#     name: default_net

networks:
  mqtt:
    ipam:
      config:
        - subnet: 172.20.0.0/24